server:
  port: 8080
#spring配置
spring:
  #国际化
  messages:
    basename: i18n.login
  #不使用thymeleaf缓存
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #数据源配置 --德鲁伊连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.31.4.246:3306/boot_db?useSSL=false
    username: zhangguimin
    password: 1991820
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #redis地址
  redis:
    host: 118.31.4.246
    database: 0
    port: 6388
    password: 1991820